const avatarData = [
    {
        family: "Noob",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822395/RecipeAssets/ForoAvatar/common01_ju9ee1.png",
        price: 5,
        type: "Common",
        id: 1,
        users: [],
    },
    {
        family: "Noob",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822395/RecipeAssets/ForoAvatar/common02_j6jkz5.png",
        price: 5,
        type: "Common",
        id: 2,
        users: [],
    },
    {
        family: "Noob",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822395/RecipeAssets/ForoAvatar/common03_ddwehm.png",
        price: 5,
        type: "Common",
        id: 3,
        users: [],
    },
    {
        family: "Noob",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822395/RecipeAssets/ForoAvatar/common04_k0gb0p.png",
        price: 5,
        type: "Common",
        id: 4,
        users: [],
    },
    {
        family: "Noob",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822395/RecipeAssets/ForoAvatar/common05_wkqp9h.png",
        price: 5,
        type: "Common",
        id: 5,
        users: [],
    },
    {
        family: "Noob",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822395/RecipeAssets/ForoAvatar/special_rumjg3.png",
        price: 25,
        type: "Special",
        id: 6,
        users: [],
    },
    {
        family: "Amateur",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822451/RecipeAssets/ForoAvatar/common01_fhx3fu.png",
        price: 10,
        type: "Common",
        id: 7,
        users: [],
    },
    {
        family: "Amateur",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822451/RecipeAssets/ForoAvatar/common02_bedxdr.png",
        price: 10,
        type: "Common",
        id: 8,
        users: [],
    },
    {
        family: "Amateur",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822451/RecipeAssets/ForoAvatar/common03_xzoji9.png",
        price: 10,
        type: "Common",
        id: 9,
        users: [],
    },
    {
        family: "Amateur",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822451/RecipeAssets/ForoAvatar/common04_v8kko3.png",
        price: 10,
        type: "Common",
        id: 10,
        users: [],
    },
    {
        family: "Amateur",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822451/RecipeAssets/ForoAvatar/common05_cg2ofv.png",
        price: 10,
        type: "Common",
        id: 11,
        users: [],
    },
    {
        family: "Amateur",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822451/RecipeAssets/ForoAvatar/Special_cuz39x.png",
        price: 50,
        type: "Special",
        id: 12,
        users: [],
    },
    {
        family: "Pro",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822508/RecipeAssets/ForoAvatar/common01_dn7cei.png",
        price: 20,
        type: "Common",
        id: 13,
        users: [],
    },
    {
        family: "Pro",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822508/RecipeAssets/ForoAvatar/common02_kn2tkf.png",
        price: 20,
        type: "Common",
        id: 14,
        users: [],
    },
    {
        family: "Pro",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822508/RecipeAssets/ForoAvatar/common03_wjhpyt.png",
        price: 20,
        type: "Common",
        id: 15,
        users: [],
    },
    {
        family: "Pro",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822508/RecipeAssets/ForoAvatar/common04_ysunmc.png",
        price: 20,
        type: "Common",
        id: 16,
        users: [],
    },
    {
        family: "Pro",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822508/RecipeAssets/ForoAvatar/common05_ie4mxd.png",
        price: 20,
        type: "Common",
        id: 17,
        users: [],
    },
    {
        family: "Pro",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822508/RecipeAssets/ForoAvatar/Special_jzofh9.png",
        price: 100,
        type: "Special",
        id: 19,
        users: [],
    },
];

const familyTopicData = [
    {
        title: "Trends",
        logo: "https://cdn2.iconfinder.com/data/icons/startup-butterscotch-vol-1/512/Long_Term_Goals-512.png",
        topics: [],
        id: 1,
    },
    {
        title: " News",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Circle-icons-news.svg/1200px-Circle-icons-news.svg.png",
        topics: [],
        id: 2,
    },
    {
        title: "Videogames",
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Video-Game-Controller-Icon-IDV-green.svg/1024px-Video-Game-Controller-Icon-IDV-green.svg.png",
        topics: [],
        id: 3,
    },
    {
        title: "Politics",
        logo: "https://png.pngtree.com/png-vector/20190729/ourlarge/pngtree-politics-law-campaign-vote-blue-dotted-line-line-icon-png-image_1622013.jpg",
        topics: [],
        id: 4,
    },
    {
        title: "Animals",
        logo: "https://cdn-icons-png.flaticon.com/512/2319/2319663.png",
        topics: [],
        id: 5,
    },
    {
        title: "Sport",
        logo: "https://www.seekpng.com/png/full/428-4281120_icon-1024-fit-for-work-icon.png",
        topics: [],
        id: 6,
    },
    {
        title: "Food",
        logo: "https://cdn-icons-png.flaticon.com/512/4065/4065741.png",
        topics: [],
        id: 7,
    },
    {
        title: "Bussines",
        logo: "https://www.shareicon.net/data/512x512/2016/08/18/809360_graph_512x512.png",
        topics: [],
        id: 8,
    },
    {
        title: "Investments",
        logo: "https://cdn-icons-png.flaticon.com/512/3749/3749892.png",
        topics: [],
        id: 9,
    },
    {
        title: "Literature",
        logo: "https://www.shareicon.net/data/512x512/2016/09/21/832387_book_512x512.png",
        topics: [],
        id: 10,
    },
    {
        title: "Movies",
        logo: "https://icon-library.com/images/free-movies-icon/free-movies-icon-16.jpg",
        topics: [],
        id: 11,
    },
    {
        title: "Geek",
        logo: "https://cdn.iconscout.com/icon/free/png-256/geek-2-160919.png",
        topics: [],
        id: 12,
    },
];

const avatarFamilyData = [
    {
        family: "Noob",
        avatarList: [],
        avatarSpecial: [],
        id: 1,
    },
    {
        family: "Amateur",
        avatarList: [],
        avatarSpecial: [],
        id: 2,
    },
    {
        family: "Pro",
        avatarList: [],
        avatarSpecial: [],
        id: 3,
    },
];

export { avatarData, familyTopicData, avatarFamilyData };
