export const avatarData = [
    {
        family: "Noob",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822395/RecipeAssets/ForoAvatar/common01_ju9ee1.png",
        price: 5,
        type: "Common",
        id: 1,
    },
    {
        family: "Noob",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822395/RecipeAssets/ForoAvatar/common02_j6jkz5.png",
        price: 5,
        type: "Common",
        id: 2,
    },
    {
        family: "Noob",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822395/RecipeAssets/ForoAvatar/common03_ddwehm.png",
        price: 5,
        type: "Common",
        id: 3,
    },
    {
        family: "Noob",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822395/RecipeAssets/ForoAvatar/common04_k0gb0p.png",
        price: 5,
        type: "Common",
        id: 4,
    },
    {
        family: "Noob",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822395/RecipeAssets/ForoAvatar/common05_wkqp9h.png",
        price: 5,
        type: "Common",
        id: 5,
    },
    {
        family: "Noob",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822395/RecipeAssets/ForoAvatar/special_rumjg3.png",
        price: 25,
        type: "Special",
        id: 6,
    },
    {
        family: "Pro",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822451/RecipeAssets/ForoAvatar/common01_fhx3fu.png",
        price: 10,
        type: "Common",
        id: 7,
    },
    {
        family: "Pro",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822451/RecipeAssets/ForoAvatar/common02_bedxdr.png",
        price: 10,
        type: "Common",
        id: 8,
    },
    {
        family: "Pro",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822451/RecipeAssets/ForoAvatar/common03_xzoji9.png",
        price: 10,
        type: "Common",
        id: 9,
    },
    {
        family: "Pro",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822451/RecipeAssets/ForoAvatar/common04_v8kko3.png",
        price: 10,
        type: "Common",
        id: 10,
    },
    {
        family: "Pro",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822451/RecipeAssets/ForoAvatar/common05_cg2ofv.png",
        price: 10,
        type: "Common",
        id: 11,
    },
    {
        family: "Pro",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822451/RecipeAssets/ForoAvatar/Special_cuz39x.png",
        price: 50,
        type: "Special",
        id: 12,
    },
    {
        family: "Boss",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822508/RecipeAssets/ForoAvatar/common01_dn7cei.png",
        price: 20,
        type: "Common",
        id: 13,
    },
    {
        family: "Boss",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822508/RecipeAssets/ForoAvatar/common02_kn2tkf.png",
        price: 20,
        type: "Common",
        id: 14,
    },
    {
        family: "Boss",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822508/RecipeAssets/ForoAvatar/common03_wjhpyt.png",
        price: 20,
        type: "Common",
        id: 15,
    },
    {
        family: "Boss",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822508/RecipeAssets/ForoAvatar/common04_ysunmc.png",
        price: 20,
        type: "Common",
        id: 16,
    },
    {
        family: "Boss",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822508/RecipeAssets/ForoAvatar/common05_ie4mxd.png",
        price: 20,
        type: "Common",
        id: 17,
    },
    {
        family: "Boss",
        img: "https://res.cloudinary.com/oscar-perez/image/upload/v1653822508/RecipeAssets/ForoAvatar/Special_jzofh9.png",
        price: 100,
        type: "Special",
        id: 19,
    },
];
